export  { default as AcademicRegisterPage}  from './AcademicRegisterPage/AcademicRegisterPage';
export  {default as CourseRegistryPage}  from './CourseRegistryPage/CourseRegistryPage';
export  {default as DefenseRequestPage}  from './DefenseRequestPage/DefenseRequestPage';
export  {default as ExternalMemberRegistryPage}  from './ExternalMemberRegistryPage/ExternalMemberRegistryPage';
export  {default as HomePage}  from './HomePage/HomePage';
export  {default as ProfessorRegistryPage}  from './ProfessorRegistryPage/ProfessorRegistryPage';
export  {default as LoginRequestPage} from './LoginRequestPage/LoginRequestPage';
export  {default as ForgotPasswordPage} from './ForgotPasswordPage/ForgotPasswordPage';
export  {default as ResetPasswordPage} from './ResetPasswordPage/ResetPasswordPage';
export  {default as AcademicsRequestsPage} from './AcademicsRequestsPage/AcademicsRequestsPage';
export  {default as HomeScreenStudentPage} from './HomeScreenStudentPage/HomeScreenStudentPage';
